-- Average count of employees.

SELECT TYPE
  ,
  COUNT(*) AS "Number of Employees"
FROM
  employee
GROUP BY TYPE;


-- Time spent by each doctor.

SELECT
  employee.firstName,
  employee.lastName,
  SEC_TO_TIME(
    SUM(
      TIME_TO_SEC(
        CASE WHEN appointment.startTime IS NOT NULL AND appointment.endTime IS NULL THEN TIMEDIFF(NOW(), appointment.startTime) ELSE TIMEDIFF(
          appointment.endTime,
          appointment.startTime
        )
        END)
    )
  ) AS "Time Taken"
FROM
  employee
JOIN
  appointment
ON
  appointment.empID = employee.id AND appointment.status IN("Done", "Inprogress")
WHERE
  employee.type = "Doctor"
GROUP BY
  employee.id;



-- Patient and Doctor info order by patient name and doctor name.

SELECT
  patient.firstName,
  patient.lastName,
  employee.firstName,
  employee.lastName
FROM
  patient
JOIN
  appointment
ON
  appointment.patientID = patient.id
JOIN
  employee
ON
  appointment.empID = employee.id
WHERE
  employee.type = "Doctor"
ORDER BY
  patient.firstName,
  patient.lastName,
  employee.firstName;


-- Revenue generated by each doctor

SELECT
  employee.firstName,
  employee.lastName,
  SUM(bill.amount)
FROM
  bill
JOIN
  appointment
ON
  appointment.ID = bill.apptID
JOIN
  employee
ON
  appointment.empID = employee.id
GROUP BY
  employee.id
ORDER BY
  employee.firstName ASC;


-- Show patients whose treatment is in progress.

SELECT
  patient.firstName,
  patient.lastName
FROM
  appointment
JOIN
  patient
ON
  appointment.patientID = patient.id
WHERE
  (appointment.status = "InProgress");



-- Show patient name, doctor info, appt detail, bill paid if applicable else N/A. 

SELECT
  patient.firstName,
  patient.lastName,
  employee.firstName,
  employee.lastName,
  appointment.causeOfVisit,
  appointment.startTime,
  appointment.endTime,
  (
    CASE WHEN appointment.status = "InProgress" THEN "N/A" WHEN bill.Status IS NOT NULL THEN bill.Status ELSE "N/A"
  END
) AS "Bill Status"
FROM
  appointment
JOIN
  patient
ON
  appointment.patientID = patient.id
JOIN
  employee
ON
  employee.id = appointment.empID
LEFT JOIN
  bill
ON
  bill.apptID = appointment.id
